# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickets < Formula
  desc "Linear-style ticket tracker where every ticket is a markdown file"
  homepage "https://github.com/stepandel/tickets-md"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.10/tickets_0.1.10_darwin_amd64.tar.gz"
      sha256 "05d028d2b6281134a3470b6b005d825257fe718bc688b4f8ed3872bd4b99fc0a"

      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.10/tickets_0.1.10_darwin_arm64.tar.gz"
      sha256 "d54db7e046b1cb953d5fbbd60cc62413efd8141314edfb3cb341720e1a93e8b5"

      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.10/tickets_0.1.10_linux_amd64.tar.gz"
      sha256 "89711b0aed6a06c66d56da21ae2aaada56ad02a9ea6bdc5581a33027078d77fd"
      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.10/tickets_0.1.10_linux_arm64.tar.gz"
      sha256 "a189376bf9b91f679d2dca28e479ac2b7597d6e7fd59d4ad3a41ff32c295a20b"
      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
  end

  test do
    system "#{bin}/tickets", "--version"
  end
end
