# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickets < Formula
  desc "Linear-style ticket tracker where every ticket is a markdown file"
  homepage "https://github.com/stepandel/tickets-md"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.8/tickets_0.1.8_darwin_amd64.tar.gz"
      sha256 "3f85d189dc9d215d657f84f3e3026f9fd78ff3aa06703601a9d34c5669fcf9cd"

      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.8/tickets_0.1.8_darwin_arm64.tar.gz"
      sha256 "9417c0da8cc12982955444e83e7bff5dac21f6dd65e7a0efa5d63c213c1b7d3d"

      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.8/tickets_0.1.8_linux_amd64.tar.gz"
      sha256 "e0a1edaf985caf622cba3953a6ae394572834003d9e0c0aacc271ff7c6920f9a"
      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stepandel/tickets-md/releases/download/v0.1.8/tickets_0.1.8_linux_arm64.tar.gz"
      sha256 "df3c7e1f0b9312f70b8b48f9f6b8074cc43de9a9c983523533a0e94dcc9fb3da"
      define_method(:install) do
        bin.install "tickets"
        generate_completions_from_executable(bin/"tickets", "completion")
      end
    end
  end

  test do
    system "#{bin}/tickets", "--version"
  end
end
